### ISSUE TITLE
[Suggestion] Desktop App

### ISSUE THREAD

**Issue by Atlas7005** [DevLeoko/AdvancedGUI-Web#4]
Just a quick suggestion here.

I feel like it would be an amazing idea to make this into a Desktop App, using Electron or something like that.
I think that would be much better since not everybody wants to load up a website each time, and it just fits better as a Desktop App in my opinion.

Great Work by the way!

**Comment by DevLeoko** [comment]
I don't really see any advantage of having this as a real desktop application. If you need faster access to the page from your desktop then you can simply create a shortcut. Chrome even has a feature to add a shortcut that opens in an own application window so it looks like a native application. Wrapping this PWA in some framework like Electro would in my opinion only add unnecessary build and deployment complexity.
Also, note that most people probably don't use this on a daily basis and thus don't want to install an application.

Thank tough for your suggestion.

**Comment by Atlas7005** [comment]
> I don't really see any advantage of having this as a real desktop application. If you need faster access to the page from your desktop then you can simply create a shortcut. Chrome even has a feature to add a shortcut that opens in an own application window so it looks like a native application. Wrapping this PWA in some framework like Electro would in my opinion only add unnecessary build and deployment complexity.
> Also, note that most people probably don't use this on a daily basis and thus don't want to install an application.
> 
> Thank tough for your suggestion.

I see. You make a decent point 😄
