### ISSUE TITLE
npm i crash

### ISSUE THREAD

**Issue by tlgnkl** [DevLeoko/AdvancedGUI-Web#7]
Hi, it looks like the code contains errors. Can you guess what this is related to?
![image](https://user-images.githubusercontent.com/67519432/147872673-6344e26e-1d4d-45e0-92cc-9314494a7344.png)
![image](https://user-images.githubusercontent.com/67519432/147872677-99f21165-4635-4a74-b957-7b77e573db98.png)
![image](https://user-images.githubusercontent.com/67519432/147872685-0368b814-a04e-45f8-93b8-8848442481f8.png)
![image](https://user-images.githubusercontent.com/67519432/147872689-30d51687-1041-4af5-a422-6879d14cef22.png)
![image](https://user-images.githubusercontent.com/67519432/147872697-b5630d63-ccae-40b8-8447-352d092dba42.png)

**Comment by DevLeoko** [comment]
Sorry for the late reply, I'm not sure which dependency (or possibly something else) is causing this error but it seems that to run `npm install` for the webpanel you are required to have python installed on your system

**Comment by Kanorto** [comment]
Everything works for me, maybe there is a gap in your Npm? and really don`t install python?
