### ISSUE TITLE
How i delete license?

### ISSUE THREAD

**Issue by Kanorto** [DevLeoko/AdvancedGUI-Web#8]
I would like to remove the licenses because this plugin was given to me by a friend

**Comment by Hopefuls** [comment]
The Dev is planning on allowing adding guest licenses, contact leoko to get the license key reset

**Comment by Kanorto** [comment]
Where can I find a backend server to install it myself?

**Comment by Kanorto** [comment]
and how can i contact leoko

**Comment by Kanorto** [comment]
Dev branch already supports its own licenses or what?

**Comment by DevLeoko** [comment]
The plugin is not meant to be shared except within the server staff. So to obtain a license you should purchase the plugin. The licensing system can not be removed as the backend export server code is closed source.

**Comment by Kanorto** [comment]
what if you remove the license code?

**Comment by DevLeoko** [comment]
The export step is done on our backend server which you need the license key for. So if you remove the license key input in the frontend your requests will simply be denied by the server

**Comment by Kanorto** [comment]
Where can I see sample code for one such GUI so I can make my own?

**Comment by DevLeoko** [comment]
Do you mean your own export server?

**Comment by Kanorto** [comment]
yes, of course

**Comment by DevLeoko** [comment]
You are not intended to code your own export server. If you want to use our software you will have to purchase a license.
