### ISSUE TITLE
Infinite Loop/Loading of Images

### ISSUE THREAD

**Issue by galexrt** [DevLeoko/AdvancedGUI-Web#9]
I'm currently trying to build a GUI and the web app is freezing up the tab in Chromium (96.0.4664.45) and Firefox (96.0.3) for me after around 30 seconds - 2 minutes or so.

It seems that the app is loading the image every few milliseconds:
![image](https://user-images.githubusercontent.com/3718398/153589677-ec190e0a-b747-4f99-a00e-57c638d53f53.png)

It just keeps going and doesn't stop.
I have tried it on the netlify (master branch) and advancedgui.app versions.

Please let me know if you need any more information.

**Comment by DevLeoko** [comment]
Hey there, thanks for the bug report. I am not able to reproduce this issue, could you tell me step by step how you get this to occur? If it is a complex GUI and you don't know what is causing the bug, you could also DM me your layout file on discord.

**Comment by galexrt** [comment]
I have the issue with this simple layout using template and replica: [StaffList.json.txt](https://github.com/DevLeoko/AdvancedGUI-Web/files/8083489/StaffList.json.txt)

**Comment by DevLeoko** [comment]
Thanks for providing this example, I have been able to reproduce the error now. I'll try to release a fix in the next few days 👍

**Comment by DevLeoko** [comment]
Sorry for the delay, this issue should now be fixed - thanks again for the report
